# Generated by Django 2.2.4 on 2020-08-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('network', models.CharField(max_length=15)),
                ('release_date', models.CharField(max_length=8)),
                ('desc', models.TextField(verbose_name='Show description')),
            ],
        ),
    ]
