# Generated by Django 2.2.4 on 2020-08-14 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='desc',
            field=models.TextField(verbose_name='old_dojo'),
        ),
    ]
