# Generated by Django 2.2.4 on 2020-08-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0004_remove_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old_dojo'),
            preserve_default=False,
        ),
    ]
